version: '3'
services:
  python27:
    container_name: buildpython
    image: python:2.7.18.shared
    build:
      dockerfile: ./Dockerfile.python
      context: .

  mystic:
    container_name: mysticbbs
    image: mystic:112A45
    build:
      dockerfile: ./Dockerfile.mystic
      context: .
      args:
        USER: ${USER}
    depends_on:
      - python27
    env_file:
      - .env
    ports:
      - "50023:23"
      - "44554:24554"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./mystic_a45:/mystic
    restart: always
